# Generated by Django 3.2.8 on 2021-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211024_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
